### ISSUE TITLE
[Feature]: flag to delete injected docs from modules

### ISSUE THREAD

**Issue by t0mk** [linode/ansible-specdoc#10]
### Description

The `-j` flag is:

```
-j, --inject          Inject the output documentation into the `DOCUMENTATION`, `RETURN`, and `EXAMPLES` fields of input module.
```

That is really great functionality and useful for the ansible sanity tests and sphinx doc generation, but it would be nice to be able to clean up the module script, as the doc strings can be very long. I sometimes wish the docs just wouldn't be there, as it's pain to handle and search through a python scripts with 100s of lines of string literals, not sure if others feel the same.

It would be good to have a flag that removes values of  `DOCUMENTATION`, `RETURN`, and `EXAMPLES` in the module scripts and sets them to empty strings

```python
DOCUMENTATION = ""
RETURN = ""
EXAMPLES = ""
```
I'm thinking that `ansible-spedoc --inject` would be run just before release (or git commit). Otherwise one could work with leaner script.

**Comment by lgarber-akamai** [comment]
This functionality has been added in `v0.0.13`. Thanks for the suggestion!
