### ISSUE TITLE
[Feature]: show how to import SpecDocMeta and other classes in README

### ISSUE THREAD

**Issue by t0mk** [linode/ansible-specdoc#8]
### Description

Hey, I'm just trying to use ansible-specdoc, and it took me a while to figure that I need to

```python
from ansible_specdoc.object import SpecDocData, ...
```

.. in order to use the project in my ansible module. It would be good if it would be in the examples or mentioned in the readme.

**Comment by lgarber-akamai** [comment]
I've fleshed out the README a bit more with better examples. Let me know if there are any other details we can add.
